minor tweaks

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,6 +26,7 @@ jobs:
       jar: ${{ steps.jar.outputs.jar }}
       version: ${{ steps.version.outputs.version }}
       game_version: ${{ steps.game_version.outputs.game_version }}
+      java_version: ${{ steps.java_version.outputs.java_version }}
 
     steps:
       - name: Checkout repository
@@ -34,11 +35,39 @@ jobs:
       - name: Validate Gradle wrapper
         uses: gradle/actions/wrapper-validation@v6
 
+      - name: Read Java version
+        id: java_version
+        shell: bash
+        run: |
+          JAVA_VERSION=$(sed -n 's/^java_version=//p' gradle.properties | head -n1 | tr -d '[:space:]')
+
+          if [ -z "$JAVA_VERSION" ]; then
+            echo "Could not determine Minecraft version."
+            exit 1
+          fi
+
+          echo "Minecraft version: $JAVA_VERSION"
+          echo "java_version=$JAVA_VERSION" >> "$GITHUB_OUTPUT"
+
+      - name: Read mod version
+        id: version
+        shell: bash
+        run: |
+          VERSION=$(sed -n 's/^mod_version=//p' gradle.properties | head -n1 | tr -d '[:space:]')
+
+          if [ -z "$VERSION" ]; then
+            echo "Could not determine mod version."
+            exit 1
+          fi
+
+          echo "Mod version: $VERSION"
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+
       - name: Set up JDK 25
         uses: actions/setup-java@v5
         with:
           distribution: temurin
-          java-version: "25"
+          java-version: ${{ steps.java_version.outputs.java_version }}
           check-latest: true
 
       - name: Set up Gradle
@@ -74,20 +103,6 @@ jobs:
 
           echo "Found: $JAR"
           echo "jar=$JAR" >> "$GITHUB_OUTPUT"
-
-      - name: Read mod version
-        id: version
-        shell: bash
-        run: |
-          VERSION=$(sed -n 's/^mod_version=//p' gradle.properties | head -n1 | tr -d '[:space:]')
-
-          if [ -z "$VERSION" ]; then
-            echo "Could not determine mod version."
-            exit 1
-          fi
-
-          echo "Mod version: $VERSION"
-          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
 
       - name: Read Minecraft version
         id: game_version
